### ISSUE TITLE
results on rain1400 by DDN ？

### ISSUE THREAD

**Issue by liang233** [csdwren/PReNet#1]
hello, This result is  re-trained? I do not find the result in original paper .thanks
![图片](https://user-images.githubusercontent.com/8869756/54933138-0a981980-4f57-11e9-8940-78cef9ebfec9.png)

**Comment by csdwren** [comment]
The results on Rain1400 are generated using their released model that can be found from the first author's homepage. By the way, the quantitative metrics in recent deraining papers are not consistent, and thus the quantitative values usually cannot be copied directly. In this paper, we try our best to make a fair comparison. On Rain1400, DDN is developed based on this dataset, and so we think it is reasonable to directly call the released model. On Rain100H and Rain100L, the results of JORDER are available, and so the papers that have consistent quantitative metric with JORDER on Rain100H and Rain100L can be copied. But for some methods, e.g., RESCAN, the reported metrics in the paper are very different from those in other papers, and so we re-train the models.

**Comment by liang233** [comment]
Thanks, I have another question, If one solution uses bigger patch to train,I think it will get better results. In 
derain task, is the size of train image important？

**Comment by csdwren** [comment]
I did not try other settings for PReNet. Actually the training parameters of PReNet are not carefully tuned. I think it is not hard to obtain better results by further tuning training parameters.

**Comment by liang233** [comment]
thanks
