### ISSUE TITLE
Data set path

### ISSUE THREAD

**Issue by FUNGERN** [csdwren/PReNet#14]
You have 4 .py training files (train_PReNet, train_PRN, train_PReNet_r, train_PRN_r), but you have 3 training datasets (RainTrainH, RainTrainL, and Rain12600). When filling in the path, is there any specific .py corresponding to a specific training set path, or are these three optional?

**Comment by csdwren** [comment]
Please read readme.md, and follow train_*.sh

**Comment by FUNGERN** [comment]
@csdwren readme.md does not write the path, and train _ * .sh cannot be opened, please tell me directly

**Comment by csdwren** [comment]
click the link to open it [https://github.com/csdwren/PReNet/blob/master/train_PReNet.sh](https://github.com/csdwren/PReNet/blob/master/train_PReNet.sh)

**Comment by FUNGERN** [comment]
@csdwren  thanks，and is it an absolute path？
E.g
# Rain100H
python train_PReNet_r.py --/data/derain/PReNet/logs/Rain100H/PReNet_r --/data/derain/PReNet/datasets/train/RainTrainH
