### ISSUE TITLE
How to put 100H, 100L and 12600 together to train a model?

### ISSUE THREAD

**Issue by FUNGERN** [csdwren/PReNet#16]
Hello, thank you for your contribution!
I would like to ask how to put three models of 100H, 100L and 12600 together to train a model? If you train together, will you still train for 100 epochs? Will it be a waste of time?
Looking forward to your reply, thanks.

**Comment by csdwren** [comment]
You need to write a new "prepare_data_xxx" function in DerainDataset.py by reading the images pairs in these three datasets. But you can randomly select patches to save h5 file to reduce the training samples, whose performance is very close the the dense sampling. Especially, Rain12600 has much more images than the others, the patches should be sampled more sparsely.

**Comment by FUNGERN** [comment]
@csdwren Thank you very much for your answer. I saw the comment that it is also possible to test the "real" dataset with a 100H training model, but the effect is not as good as in the paper. I want to implement the training model of your three datasets to test the "real" dataset, but my programming skills are not good. Can you provide DerainDataset.py of the merged dataset? So that I can test the "real" dataset. Greatful. Thank you!

**Comment by FUNGERN** [comment]
@csdwren  Hi, I re-integrated the data set, and I want to generate a .h5 file, but he reports an error. I also wrote 
> --preprocess
 True in the `train_PReNet.sh file`.
Why did you report that mistake?

unkown datasets: please define prepare data function in DerainDataset.py
Loading dataset ...

Traceback (most recent call last):
  File "train_PReNet.py", line 144, in <module>
    main()
  File "train_PReNet.py", line 39, in main
    dataset_train = Dataset(data_path=opt.data_path)
  File "/data/derain/PReNet/DerainDataset.py", line 191, in __init__
    target_h5f = h5py.File(target_path, 'r')
  File "/home/pytor/.conda/envs/pytorch0.4/lib/python3.6/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/home/pytor/.conda/envs/pytorch0.4/lib/python3.6/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '/data/derain/PReNet/datasets/train/Rain9854/train_target.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
(pytorch0.4) pytor@user:/data/derain/PReNet$

**Comment by flymmmfly** [comment]
> 
> 
> @csdwren Thank you very much for your answer. I saw the comment that it is also possible to test the "real" dataset with a 100H training model, but the effect is not as good as in the paper. I want to implement the training model of your three datasets to test the "real" dataset, but my programming skills are not good. Can you provide DerainDataset.py of the merged dataset? So that I can test the "real" dataset. Greatful. Thank you!

Could you share your solution to this idea, thank you！
