### ISSUE TITLE
rescan pretrained model

### ISSUE THREAD

**Issue by cchenghao** [csdwren/PReNet#18]
I can not find a pre-trained weight of rescan, do you have it?  can you share a copy? thanks.

**Comment by csdwren** [comment]
We only released the trained RESCAN model for Rain100H at https://pan.baidu.com/s/1Oym9G-8Bq-0FU2BfbARf8g  
![image](https://user-images.githubusercontent.com/12967408/72352014-7634b880-371c-11ea-9e3e-9e4b21fccae6.png)

**Comment by cchenghao** [comment]
> We only released the trained RESCAN model for Rain100H at https://pan.baidu.com/s/1Oym9G-8Bq-0FU2BfbARf8g
> ![image](https://user-images.githubusercontent.com/12967408/72352014-7634b880-371c-11ea-9e3e-9e4b21fccae6.png)

thanks.
