### ISSUE TITLE
No logs/Rain12 .pth files

### ISSUE THREAD

**Issue by Commin** [csdwren/PReNet#22]

**Comment by Commin** [comment]
Hello!
It seems that there are not any `.pth` files about Rain12 testing dataset in the directory `logs`.
Could you upload these files to GitHub?

**Comment by csdwren** [comment]
Rain12 dataset and Rain100L share the same model. You can call the models in logs/Rain100L/ to process Rain12.

**Comment by Commin** [comment]
Thank you for reply!
