### ISSUE TITLE
how to train only LSTM models in stages 2, 3, 4, 5, 6, and 7 and test these 6 models？

### ISSUE THREAD

**Issue by FUNGERN** [csdwren/PReNet#24]
Hi, your work is great. 
I have a question to ask you if I only want to train the LSTM model in stages  2, 3, 4, 5, 6, and 7 . Do I just need to change recurrent_iter=2,3,4,5,6,7 in networks.py and train_PReNet.py?
I don't quite understand, please tell me, thanks

**Comment by FUNGERN** [comment]
![微信截图_20200807182303](https://user-images.githubusercontent.com/49382317/89637043-2f86f580-d8dc-11ea-8e74-3ecccb1a81da.png)
![微信截图_20200807182813](https://user-images.githubusercontent.com/49382317/89637125-4cbbc400-d8dc-11ea-88d0-81526c256c0a.png)

**Comment by csdwren** [comment]
You only need to set recurrent_iter as 2,3,4,5,6,7 in train_PReNet.py.  That is to say, make sure the model is initialized with recurrent_iter stages in train_PReNet.py. 
![image](https://user-images.githubusercontent.com/12967408/89637692-2c403980-d8dd-11ea-8ab4-698a5fa4d3ec.png)

The recurrent_iter in networks.py only works when it is not specified in train_PReNet.py

**Comment by FUNGERN** [comment]
oh， thanks
