### ISSUE TITLE
no file named train_target.h5

### ISSUE THREAD

**Issue by Jamofl** [csdwren/PReNet#31]
hello! thanks a lot for your wonderful code!
I want to try ur code on my own dataset, so i create a folder named 'mydatasets' and put it in 'datasets/train/',  and put rain and norain images in this folder.

i run 'python train_PReNet.py  --preprocess True save_path  xxxx  -- data_path datasets/train/mydatasets'
and error occurs as below:
Unable to open file (unable to open file: name = ' datasets/train/mydatasets/train_target.h5')   no such file or directory

so, how to get the file train_target.h5?  looking forward  to ur response!!!

**Comment by Arican-Lee** [comment]
Have you solved this problem?
