### ISSUE TITLE
关于参数共享

### ISSUE THREAD

**Issue by liang233** [csdwren/PReNet#6]
你好，你们有没有试过每个阶段的卷积层（除了convlstm层）参数不共享的话，会降低多少？还有感觉计算y通道的psnr和rgb通道psnr的数值相差有点大，然后不同论文又都混着用，就比较麻烦

**Comment by csdwren** [comment]
你的意思是每个阶段用新的卷积层？我们没有试，不过应该也不会差，参数量变大了更容易在训练集过拟合，指标应该不会降，但generalization性能可能会下降。
现在论文计算指标的确不统一，psnr值一般是 rgb > y通道 > rgb2gray。Matlab实现的psnr、ssim和python实现的好像也不太一样。我只能保证自己论文里是统一指标。

**Comment by liang233** [comment]
也对,一般y通道的会比rgb高，所以其他方法的psnr值也变高了
